#!/bin/sh
# postrm script for pywebhooks
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy packagemeniscus


case "$1" in
	purge)
        echo "Purging pywebhooks..." >&2
        if (getent passwd pywebhooks) > /dev/null 2>&1; then
            userdel pywebhooks || true
        fi

        if (getent group pywebhooks) > /dev/null 2>&1; then
            groupdel pywebhooks || true
        fi

        [ -e /var/lib/pywebhooks ] && rm -rf /var/lib/pywebhooks
        [ -e /var/log/pywebhooks ] && rm -rf /var/log/pywebhooks
        [ -e /usr/share/pywebhooks ] && rm -rf /usr/share/pywebhooks
        [ -e /etc/pywebhooks ] && rm -rf /etc/pywebhooks
	;;

    upgrade|failed-upgrade|abort-upgrade)
        echo "upgrade ignored"
    ;;

    remove|abort-install|disappear)
        [ -e /usr/share/pywebhooks ] && rm -rf /usr/share/pywebhooks
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
