#!/bin/sh
# postinst script for pywebhooks
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
	    . /usr/share/debconf/confmodule

	    if ! (getent group pywebhooks) > /dev/null 2>&1; then
	        addgroup --quiet --system pywebhooks > /dev/null
		fi

		if ! (getent passwd pywebhooks) > /dev/null 2>&1; then
		    adduser --quiet --system --home /var/lib/pywebhooks --ingroup pywebhooks --no-create-home --shell /bin/false pywebhooks
		fi

		chmod 0755 /etc/init.d/pywebhooks

		if [ ! -d /var/log/pywebhooks ]; then
            mkdir /var/log/pywebhooks
            chown -R pywebhooks:adm /var/log/pywebhooks/
            chmod 0755 /var/log/pywebhooks/
        fi

        if [ ! -d /var/lib/pywebhooks ]; then
            mkdir /var/lib/pywebhooks
            chown pywebhooks:pywebhooks -R /var/lib/pywebhooks/ /etc/pywebhooks
            chmod -R 0755 /etc/pywebhooks/
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
